# SOL 錢包監控配置

# gRPC 服務器配置
[grpc]
endpoint = "http://127.0.0.1:10000"

# RPC 服務器配置
[rpc]
endpoint = "http://127.0.0.1:8899"

# Web 服務器配置
[server]
host = "0.0.0.0"
port = 3000

# 監控的錢包列表
# 可以添加更多錢包
# 日誌設定
[logging]
level = "info" 

[[wallets]]
address = "7dGrdJRYtsNR8UYxZ3TnifXGjGc9eRYLq9sELwYpuuUu"
name = "7dG"

[[wallets]]
address = "As516ZAsiAzTQuR5JTP5oEucPb3irbQf4tBxKx3MDMpa"
name = "As51"